-- The application accesses PostgreSQL exclusively from its authenticated server.
-- Supabase exposes the public schema through its Data API, so deny direct
-- anon/authenticated access unless explicit policies are added in the future.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Contact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Opportunity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OfferTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GeneratedOffer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Campaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Sequence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReviewItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PipelineDeal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SourceConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SystemSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActivityLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Suppression" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyMetric" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProviderUsage" ENABLE ROW LEVEL SECURITY;
