import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { config } from "dotenv";
import pg from "pg";

export function loadEnvironment() {
  config({ path: ".env.local", quiet: true });
  config({ path: ".env", quiet: true });
}
export async function prepareLocalDatabase() {
  loadEnvironment();
  if (!process.env.DATABASE_URL) {
    if (process.env.NODE_ENV === "production" || process.env.VERCEL) throw new Error("DATABASE_URL is required in production.");
    const password = crypto.randomBytes(24).toString("hex");
    const adminPassword = crypto.randomBytes(15).toString("base64url");
    // Never overwrite the user's environment. Append only missing local defaults.
    const defaults = {
      DATABASE_URL: `postgresql://mdl:${password}@127.0.0.1:54329/mdl_lead_engine?schema=public`,
      LOCAL_DATABASE: "true", LOCAL_DB_PASSWORD: password,
      NEXTAUTH_SECRET: crypto.randomBytes(32).toString("hex"), NEXTAUTH_URL: "http://localhost:3000",
      APP_URL: "http://localhost:3000", ADMIN_EMAIL: "matthew@mdl.local", ADMIN_PASSWORD: adminPassword, DRY_RUN: "true", SEED_DEMO: "true",
    };
    const lines = Object.entries(defaults).filter(([key]) => !process.env[key]);
    fs.appendFileSync(".env", "\n# Local development — generated by MDL Lead Engine\n" + lines.map(([key,value]) => `${key}=${value}`).join("\n") + "\n", { mode: 0o600 });
    for (const [key, value] of lines) process.env[key] = value;
    console.log("Local environment created in .env. Your private sign-in credentials are ADMIN_EMAIL and ADMIN_PASSWORD.");
  }
  if (process.env.LOCAL_DATABASE !== "true") return null;
  const url = new URL(process.env.DATABASE_URL);
  if (!["localhost", "127.0.0.1"].includes(url.hostname)) throw new Error("LOCAL_DATABASE requires a loopback database URL.");
  const existing = new pg.Client({ connectionString: process.env.DATABASE_URL, connectionTimeoutMillis: 1500 });
  try { await existing.connect(); await existing.end(); console.log("Using running local PostgreSQL."); return null; }
  catch { await existing.end().catch(() => {}); }
  const { default: EmbeddedPostgres } = await import("embedded-postgres");
  const directory = path.resolve(".local/postgres");
  fs.mkdirSync(path.dirname(directory), { recursive: true });
  const cluster = new EmbeddedPostgres({ databaseDir: directory, user: decodeURIComponent(url.username), password: decodeURIComponent(url.password),
    port: Number(url.port), persistent: true, authMethod: "scram-sha-256", postgresFlags: ["-h", "127.0.0.1"],
    onLog: () => {}, onError: (error) => { const message = String(error); if (/FATAL|PANIC/.test(message)) console.error(message); },
  });
  if (!fs.existsSync(path.join(directory, "PG_VERSION"))) await cluster.initialise();
  await cluster.start();
  const client = cluster.getPgClient();
  await client.connect();
  const dbName = url.pathname.slice(1);
  if (!/^[A-Za-z0-9_]+$/.test(dbName)) { await client.end(); throw new Error("The local database name must contain only letters, digits and underscores."); }
  const found = await client.query("SELECT pg_encoding_to_char(encoding) AS encoding FROM pg_database WHERE datname = $1", [dbName]);
  // initdb follows the Windows system locale and can produce a WIN1252 cluster. Scraped web
  // pages are UTF-8: one emoji or zero-width character would abort the write. template0 lets
  // this database be UTF8 whatever the cluster default is.
  if (!found.rowCount) await client.query(`CREATE DATABASE "${dbName}" WITH ENCODING 'UTF8' TEMPLATE template0 LC_COLLATE 'C' LC_CTYPE 'C'`);
  else if (found.rows[0].encoding !== "UTF8") {
    await client.end();
    throw new Error(`The local database "${dbName}" uses ${found.rows[0].encoding} instead of UTF8, so web content cannot be stored. Stop the app, delete the .local/postgres folder, then run npm run dev again to recreate it.`);
  }
  await client.end();
  console.log(`PostgreSQL ready on 127.0.0.1:${url.port} (persistent .local/postgres).`);
  return cluster;
}
